name:                Redux
version:             0.1.0.0
github:              "githubuser/Redux"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Redux#readme>

dependencies:
- base >= 4.7
- random
- containers
- dlist
- lens
- gloss >= 1.13
- mtl
- constrained-dynamic
- HList
- bmp
- bytestring

default-extensions:
- TemplateHaskell
- RankNTypes
- DeriveAnyClass
- FlexibleInstances
- GADTs
- ScopedTypeVariables
- MultiParamTypeClasses
- DataKinds
- ViewPatterns

library:
  source-dirs: src

executables:
  Redux-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Redux

tests:
  Redux-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Redux
    - HTF
    - HUnit
